package GameCore;

public class GameEnums {
    public enum SuperType {

        BASIC, SNOW, LEGENDARY, WORLD, ELITE, ONGOING

    }

    public enum Type {

        CREATURE, ENCHANTMENT, INSTANT, SORCERY, LAND,
        PLANESWALKER, ARTIFACT, TRIBAL

    }

    public enum SubType {

        // Enchantments
        AURA, CURSE, SHRINE,

        // Artifacts
        CONTRAPTION, EQUIPMENT, FORTIFICATION,

        // Lands
        DESERT, GATE, LAIR, LOCUS, URZAS, MINE, POWER_PLANT, TOWER,
        PLAINS, ISLAND, SWAMP, MOUNTAIN, FOREST,

        // Planes (not used)
        ALARA, ARKHOS, AZGOL, BELENON, BOLAS_MEDITAION_REALM, DOMINARA,
        EQUILOR, ERGAMON, FABACIN, IQUATANA, INNISTRAD, IR, KALDHEIM,
        KAMIGAWA, KARSUS, KEPHALAI, KOLBAHAN, KYNETH, LORWYN, LUVION,
        MERCADIA, MIRRODIN, MOAG, MONGSENG, NEW_PHYREXIA, PHYREXIA,
        PYRULEA, RABIAH, RATH, RAVNICA, REGATHA, SEGOVIA, SERRAS_REALM,
        SHADOWMOOR, SHANDALAR, ULGROTHA, VALLA, VRYN, WILDFIRE, ZENDIKAR,

        // Planeswalker
        AJANI, BOLAS, CHANDRA, DOMRI, ELSPETH, GARRUK, GIDEON, JACE,
        KARN, KOTH, LILIANA, NISSA, SARKHAN, SORIN, TAMIYO, TEZZERET,
        TIBALT, VENSER, VRASKA,

        // Spell
        ARCANE, TRAP,

        // Creature
        ADVISOR, ALLY, ANGEL, ANTEATER, ANTELOPE, APE, ARCHER, ARCHON,
        ARTIFICER, ASSASSIN, ASEMBLY_WORKER, ATOG, AUROCHS, AVATAR,

        BADGER, BARBARIAN, BASILISK, BAT, BEAR, BEAST, BEEBLE, BERSERKER,
        BIRD, BLINKMOTH, BOAR, BRINGER, BRUSHWAGG,

        CAMARID, CAMEL, CARIBOU, CARRIER, CAT, CENTAUR, CEPHALID,
        CHIMERA, CITIZEN, CLERIC, COCKATRICE, CONSTRUCT, COWARD,
        CRAB, CROCODILE, CYCLOPS,

        DAUTHI, DEMON, DESERTER, DEVIL, DJINN, DRAGON, DRAKE,
        DREADNOUGHT, DRONE, DRUID, DRYAD, DWARF,

        EFREET, ELDER, ELDRAZI, ELEMENTAL, ELEPHANT, ELF, ELK, EYE,

        FAERIE, FERRET, FISH, FLAGBEARER, FOX, FROG, FUNGUS,

        GARGOYLE, GERM, GIANT, GNOME, GOAT, GOBLIN, GOD, GOLEM, GORGON,
        GRAVEBORN, GREMLIN, GRIFFIN,

        HAG, HARPY, HELION, HIPPO, HIPPOGRIPH, HOMARID, HOMUNCULOS, HORROR,
        HORSE, HOUND, HUMAN, HYDRA, HYENA,

        ILLUSION, IMP, INCARNATION, INSECT,

        JELLYFISH, JUGGERNAUT,

        KAVU, KIRIN, KITHKIN, KNIGHT, KOBOLD,  KOR, KRAKEN,

        LAMIA, LAMMASU, LEECH, LEVIATHAN, LHURGOYF, LICID, LIZARD,

        MANTICORE, MASTICORE, MERCENARY, MERFOLK, METATHRAN, MINION,
        MINOTAUR, MONGER, MONGOOSE, MONK, MOONFOLK, MUTANT, MYR, MYSTIC,

        NAUTILUS, NEPHILIM, NIGHTMARE, NIGHTSTALKER, NINJA, NOGGLE, NOMAD, NYMPH,

        OCTOPUS, OGRE, OOZE, ORB, ORC, ORGG, OUPHE, OX, OYSTER,

        PEGASUS, PENTAVITE, PEST, PHELDDAGRIF, PHOENIX, PINCHER, PIRATE, PLANT,
        PRAETOR, PRISM,

        RABBIT, RAT, REBEL, REFLECTION, RHINO, RIGGER, ROGUE,

        SABLE, SALAMANDER, SAMURAI, SAND, SAPROLING, SATYR, SCARECROW, SCORPION,
        SCOUT, SERF, SERPENT, SHADE, SHAMAN, SHAPESHIFTER, SHEEP, SIREN, SKELETON,
        SLITH, SLIVER, SLUG, SNAKE, SOLDIER, SOLTARI, SPAWN, SPECTER, SPELLSHAPER,
        SPHINX, SPIDER, SPIKE, SPIRIT, SPLINTER, SPONGE, SQUID, SQUIRREL, STARFISH,
        SURRAKAR, SURVIVOR,

        TETRAVITE, THALAKOS, THRULL, TREEFOLK, TRISKELAVITE, TROLL, TURTLE,

        UNICORN,

        VAMPIRE, VELDAKEN, VIASHINO, VOLVER,

        WALL, WARRIOR, WIERD, WEREWOLF, WHALE, WIZARD, WOLF, WOLVERINE, WOMBAT,
        WORM, WRAITH, WURM,

        YETI,

        ZOMBIE, ZUBERA,

        //Not used
        HEAD, HERO, REVELLER
        
    }

    public enum Zone {

        COMMAND, BATTLEFIELD, EXILE_FUP, EXILE_FDN, GRAVEYARD, LIBRARY, HAND
        
    }

    public enum AbilityType {
        ACTIVE, TRIGGERED, STATIC
    }

    public enum ManaPoolDirection {
        ADD, SUB
    }
}